export const profileData = {
  id: 1,
  firstName: "Ahmed",
  lastName: "Aftab",
  userName: "ahmad.aftab",
  email: "ahmad.aft@yahoo.com",
  age: 25,
  about: "Hello, Nice to meet you",
};

export const users = [
  {
    id: 1,
    firstName: "Ahmed",
    lastName: "Aftab",
    userName: "ahmad.aftab",
    email: "ahmad.aft@yahoo.com",
    age: 25,
    about: "Hello, Nice to meet you",
  },
  {
    id: 2,
    firstName: "Ali",
    lastName: "Zubairi",
    userName: "ali.zub",
    email: "ali.zub@yahoo.com",
    age: 22,
    about: "Hello, Nice to meet you",
  },
  {
    id: 3,
    firstName: "Usama",
    lastName: "Ahmad",
    userName: "usama.ahmi",
    email: "usama.ahmi@yahoo.com",
    age: 30,
    about: "Hello, Nice to meet you",
  },
  {
    id: 4,
    firstName: "Aamir",
    lastName: "Arshad",
    userName: "amr.ash",
    email: "amr.ash@yahoo.com",
    age: 24,
    about: "Hello, Nice to meet you",
  },
  {
    id: 5,
    firstName: "Ayesha",
    lastName: "Khalid",
    userName: "princess.dolly",
    email: "princess.dolly@yahoo.com",
    age: 31,
    about: "Hello, Nice to meet you",
  },
  {
    id: 6,
    firstName: "Zoha",
    lastName: "Javed",
    userName: "zojav301",
    email: "zoha.javed511@yahoo.com",
    age: 25,
    about: "Hello, Nice to meet you",
  },
  {
    id: 7,
    firstName: "Ghulam",
    lastName: "Mustafa",
    userName: "ghulam.mustafa",
    email: "ghulam.mustafa@yahoo.com",
    age: 25,
    about: "Hello, Nice to meet you",
  },
  {
    id: 8,
    firstName: "Laraib",
    lastName: "Khawar",
    userName: "labby.malik",
    email: "labby.malik@yahoo.com",
    age: 22,
    about: "Hello, Nice to meet you",
  },
  {
    id: 9,
    firstName: "Malik",
    lastName: "Zeeshan",
    userName: "zeshan.malikk",
    email: "zeshan.malikk@yahoo.com",
    age: 35,
    about: "Hello, Nice to meet you",
  },
  {
    id: 10,
    firstName: "Zahid",
    lastName: "Cheema",
    userName: "zahid.ch",
    email: "cheema.sb@yahoo.com",
    age: 25,
    about: "Hello, Nice to meet you",
  },
];

export const friends = [
  {
    index: 1,
    id: 1,
    friendId: 5,
    isFriend: true,
  },
  {
    index: 2,
    id: 3,
    friendId: 2,
    isFriend: true,
  },
  {
    index: 3,
    id: 1,
    friendId: 2,
    isFriend: true,
  },
  {
    index: 4,
    id: 1,
    friendId: 9,
    isFriend: true,
  },
  {
    index: 5,
    id: 7,
    friendId: 2,
    isFriend: true,
  },
  {
    index: 6,
    id: 1,
    friendId: 3,
    isFriend: true,
  },
];
